version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      MONGO_URL: mongodb://db:27017/mydb
    depends_on:
      - db
    command: ["npm", "run", "dev"]

  dummy:
    build:
      context: ./dummy
    ports:
      - "3001:3001"

volumes:
  db_data:
  